annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - bump common chart version 0.0.45 -> 0.0.46
    - bump version of VM components to [v1.133.0](https://github.com/VictoriaMetrics/VictoriaMetrics/releases/tag/v1.133.0)
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Sources
      url: https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-cluster
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Docs
      url: https://docs.victoriametrics.com/victoriametrics/cluster-victoriametrics/
    - name: Changelog
      url: https://docs.victoriametrics.com/victoriametrics/changelog/
  artifacthub.io/readme: |
    # VictoriaMetrics Cluster Helm chart

    Chart documentation is available [here](https://docs.victoriametrics.com/helm/victoria-metrics-cluster/)
apiVersion: v2
appVersion: v1.133.0
dependencies:
- name: victoria-metrics-common
  repository: https://victoriametrics.github.io/helm-charts
  version: 0.0.*
description: VictoriaMetrics Cluster version - high-performance, cost-effective and
  scalable TSDB, long-term remote storage for Prometheus
home: https://github.com/VictoriaMetrics/helm-charts
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
keywords:
- victoriametrics
- vmcluster
- vmselect
- vminsert
- vmstorage
- tsdb
- monitoring
- kubernetes
- observability
- metrics
- metricsql
- timeseries
kubeVersion: '>=1.25.0-0'
name: victoria-metrics-cluster
sources:
- https://github.com/VictoriaMetrics/helm-charts
type: application
version: 0.32.0
